[package]
name = "space-sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Can't update winit bc pixels hasn't been updated to work w/ anything newer
pixels = "0.13.0"
winit = "0.28.6"
